const configs = {
  suppliers: {
    titleField: 'name',
    tableFields: [
      { key: 'name', label: 'Supplier Name' },
      { key: 'country', label: 'Country' },
      { key: 'industry', label: 'Industry' },
      { key: 'reliability_score', label: 'Reliability', type: 'score' },
      { key: 'cost_rating', label: 'Cost Rating' },
      { key: 'lead_time_days', label: 'Lead Time (days)' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Supplier Name', required: true },
      { key: 'country', label: 'Country', required: true },
      { key: 'region', label: 'Region' },
      { key: 'industry', label: 'Industry', type: 'select', options: ['Steel Manufacturing', 'Electronics', 'Plastics', 'Textiles', 'Automotive', 'Pharmaceutical', 'Chemicals', 'Mining/Minerals', 'Furniture', 'Aerospace', 'Technology', 'Packaging', 'Tool & Die', 'Renewable Energy', 'Medical Devices', 'Food Processing'] },
      { key: 'capability', label: 'Capabilities', type: 'textarea' },
      { key: 'reliability_score', label: 'Reliability Score (0-10)', type: 'number' },
      { key: 'cost_rating', label: 'Cost Rating', type: 'select', options: ['Low', 'Low-Medium', 'Medium', 'Medium-High', 'High'] },
      { key: 'lead_time_days', label: 'Lead Time (days)', type: 'number' },
      { key: 'certifications', label: 'Certifications', type: 'textarea' },
      { key: 'contact_email', label: 'Contact Email', type: 'email' },
      { key: 'phone', label: 'Phone' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'pending', 'under_review'], default: 'active' },
    ]
  },
  'risk-assessments': {
    titleField: 'title',
    tableFields: [
      { key: 'title', label: 'Risk Title' },
      { key: 'category', label: 'Category' },
      { key: 'current_country', label: 'From' },
      { key: 'target_country', label: 'To' },
      { key: 'risk_level', label: 'Risk Level', type: 'status' },
      { key: 'risk_score', label: 'Score', type: 'score' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Supply Disruption', 'Geopolitical', 'Tariff/Trade', 'Workforce', 'Logistics', 'Regulatory', 'Environmental', 'Financial', 'Technology', 'Infrastructure', 'Operational'] },
      { key: 'current_supplier', label: 'Current Supplier' },
      { key: 'current_country', label: 'Current Country' },
      { key: 'target_country', label: 'Target Country' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'risk_score', label: 'Risk Score (0-10)', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'mitigation_strategy', label: 'Mitigation Strategy', type: 'textarea' },
      { key: 'impact_area', label: 'Impact Area', type: 'select', options: ['Production', 'Raw Materials', 'Cost', 'Operations', 'Logistics', 'Healthcare', 'Supply Chain', 'Financial', 'Security', 'Legal', 'Competitive', 'Strategic'] },
      { key: 'probability', label: 'Probability', type: 'select', options: ['Low', 'Low-Medium', 'Medium', 'Medium-High', 'High'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'monitoring', 'mitigated', 'closed'], default: 'active' },
    ]
  },
  'cost-analysis': {
    titleField: 'title',
    tableFields: [
      { key: 'title', label: 'Analysis' },
      { key: 'product_category', label: 'Category' },
      { key: 'current_location', label: 'From' },
      { key: 'target_location', label: 'To' },
      { key: 'current_annual_cost', label: 'Current Cost', type: 'currency' },
      { key: 'savings_percentage', label: 'Savings', type: 'percentage' },
      { key: 'roi_months', label: 'ROI (months)' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'product_category', label: 'Product Category' },
      { key: 'current_location', label: 'Current Location' },
      { key: 'target_location', label: 'Target Location' },
      { key: 'current_annual_cost', label: 'Current Annual Cost', type: 'number' },
      { key: 'projected_annual_cost', label: 'Projected Annual Cost', type: 'number' },
      { key: 'savings_percentage', label: 'Savings %', type: 'number' },
      { key: 'labor_cost_diff', label: 'Labor Cost Difference', type: 'number' },
      { key: 'logistics_cost_diff', label: 'Logistics Cost Difference', type: 'number' },
      { key: 'tariff_impact', label: 'Tariff Impact', type: 'number' },
      { key: 'roi_months', label: 'ROI (months)', type: 'number' },
      { key: 'recommendation', label: 'Recommendation' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'in_progress', 'completed'], default: 'draft' },
    ]
  },
  'tariff-calculations': {
    titleField: 'product_name',
    tableFields: [
      { key: 'product_name', label: 'Product' },
      { key: 'hs_code', label: 'HS Code' },
      { key: 'origin_country', label: 'Origin' },
      { key: 'tariff_rate', label: 'Rate', type: 'percentage' },
      { key: 'tariff_amount', label: 'Tariff', type: 'currency' },
      { key: 'trade_agreement', label: 'Agreement' },
      { key: 'total_landed_cost', label: 'Landed Cost', type: 'currency' },
    ],
    formFields: [
      { key: 'product_name', label: 'Product Name', required: true },
      { key: 'hs_code', label: 'HS Code' },
      { key: 'origin_country', label: 'Origin Country' },
      { key: 'destination_country', label: 'Destination Country' },
      { key: 'product_value', label: 'Product Value', type: 'number' },
      { key: 'tariff_rate', label: 'Tariff Rate %', type: 'number' },
      { key: 'tariff_amount', label: 'Tariff Amount', type: 'number' },
      { key: 'trade_agreement', label: 'Trade Agreement' },
      { key: 'effective_date', label: 'Effective Date', type: 'date' },
      { key: 'exemptions', label: 'Exemptions', type: 'textarea' },
      { key: 'total_landed_cost', label: 'Total Landed Cost', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['calculated', 'pending', 'expired'], default: 'calculated' },
    ]
  },
  'supply-chain-maps': {
    titleField: 'name',
    tableFields: [
      { key: 'name', label: 'Node Name' },
      { key: 'product_line', label: 'Product Line' },
      { key: 'tier', label: 'Tier' },
      { key: 'node_type', label: 'Type' },
      { key: 'country', label: 'Country' },
      { key: 'lead_time_days', label: 'Lead Time' },
      { key: 'risk_level', label: 'Risk', type: 'status' },
    ],
    formFields: [
      { key: 'name', label: 'Node Name', required: true },
      { key: 'product_line', label: 'Product Line' },
      { key: 'tier', label: 'Tier', type: 'select', options: ['Tier 1', 'Tier 2', 'Tier 3'] },
      { key: 'node_type', label: 'Node Type', type: 'select', options: ['Raw Material', 'Processing', 'Manufacturing', 'Assembly', 'Distribution'] },
      { key: 'location', label: 'Location' },
      { key: 'country', label: 'Country' },
      { key: 'supplier_name', label: 'Supplier Name' },
      { key: 'lead_time_days', label: 'Lead Time (days)', type: 'number' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'dependencies', label: 'Dependencies', type: 'textarea' },
      { key: 'alternatives', label: 'Alternatives', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['mapped', 'transitioning', 'reshored'], default: 'mapped' },
    ]
  },
  'compliance-checks': {
    titleField: 'title',
    tableFields: [
      { key: 'title', label: 'Compliance Check' },
      { key: 'regulation_type', label: 'Regulation' },
      { key: 'jurisdiction', label: 'Jurisdiction' },
      { key: 'compliance_status', label: 'Compliance', type: 'status' },
      { key: 'deadline', label: 'Deadline' },
      { key: 'penalty_risk', label: 'Penalty Risk', type: 'currency' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'regulation_type', label: 'Regulation Type' },
      { key: 'jurisdiction', label: 'Jurisdiction' },
      { key: 'product_category', label: 'Product Category' },
      { key: 'compliance_status', label: 'Compliance Status', type: 'select', options: ['Compliant', 'Partially Compliant', 'Non-Compliant', 'Under Review'] },
      { key: 'requirements', label: 'Requirements', type: 'textarea' },
      { key: 'gaps', label: 'Gaps', type: 'textarea' },
      { key: 'deadline', label: 'Deadline', type: 'date' },
      { key: 'responsible_party', label: 'Responsible Party' },
      { key: 'documentation_status', label: 'Documentation', type: 'select', options: ['Complete', 'In Progress', 'Incomplete'] },
      { key: 'penalty_risk', label: 'Penalty Risk ($)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['approved', 'in_review', 'action_required'], default: 'in_review' },
    ]
  },
  'transport-routes': {
    titleField: 'name',
    tableFields: [
      { key: 'name', label: 'Route' },
      { key: 'origin', label: 'Origin' },
      { key: 'destination', label: 'Destination' },
      { key: 'transport_mode', label: 'Mode' },
      { key: 'transit_time_days', label: 'Days' },
      { key: 'cost_per_unit', label: 'Cost/Unit', type: 'currency' },
      { key: 'reliability_score', label: 'Reliability', type: 'score' },
    ],
    formFields: [
      { key: 'name', label: 'Route Name', required: true },
      { key: 'origin', label: 'Origin' },
      { key: 'destination', label: 'Destination' },
      { key: 'transport_mode', label: 'Mode', type: 'select', options: ['Ocean', 'Air', 'Truck', 'Rail', 'Intermodal'] },
      { key: 'distance_km', label: 'Distance (km)', type: 'number' },
      { key: 'transit_time_days', label: 'Transit Time (days)', type: 'number' },
      { key: 'cost_per_unit', label: 'Cost per Unit', type: 'number' },
      { key: 'carbon_footprint', label: 'Carbon Footprint (kg CO2)', type: 'number' },
      { key: 'reliability_score', label: 'Reliability (0-10)', type: 'number' },
      { key: 'carrier', label: 'Carrier' },
      { key: 'frequency', label: 'Frequency', type: 'select', options: ['Daily', 'Weekly', 'Bi-weekly', 'Monthly'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'planned'], default: 'active' },
    ]
  },
  'workforce-plans': {
    titleField: 'title',
    tableFields: [
      { key: 'title', label: 'Plan' },
      { key: 'facility_location', label: 'Location' },
      { key: 'department', label: 'Department' },
      { key: 'current_headcount', label: 'Current' },
      { key: 'required_headcount', label: 'Required' },
      { key: 'estimated_cost', label: 'Cost', type: 'currency' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'facility_location', label: 'Facility Location' },
      { key: 'department', label: 'Department' },
      { key: 'current_headcount', label: 'Current Headcount', type: 'number' },
      { key: 'required_headcount', label: 'Required Headcount', type: 'number' },
      { key: 'skill_requirements', label: 'Skill Requirements', type: 'textarea' },
      { key: 'training_needs', label: 'Training Needs', type: 'textarea' },
      { key: 'hiring_timeline', label: 'Hiring Timeline' },
      { key: 'estimated_cost', label: 'Estimated Cost', type: 'number' },
      { key: 'labor_market_score', label: 'Labor Market Score (0-10)', type: 'number' },
      { key: 'retention_risk', label: 'Retention Risk', type: 'select', options: ['Low', 'Medium', 'Medium-High', 'High'] },
      { key: 'status', label: 'Status', type: 'select', options: ['planning', 'active', 'completed'], default: 'planning' },
    ]
  },
  'site-selections': {
    titleField: 'site_name',
    tableFields: [
      { key: 'site_name', label: 'Site' },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'site_type', label: 'Type' },
      { key: 'monthly_cost', label: 'Monthly Cost', type: 'currency' },
      { key: 'overall_score', label: 'Score', type: 'score' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'site_name', label: 'Site Name', required: true },
      { key: 'city', label: 'City' },
      { key: 'state', label: 'State' },
      { key: 'country', label: 'Country', default: 'United States' },
      { key: 'site_type', label: 'Site Type' },
      { key: 'area_sqft', label: 'Area (sq ft)', type: 'number' },
      { key: 'monthly_cost', label: 'Monthly Cost', type: 'number' },
      { key: 'labor_availability_score', label: 'Labor Score (0-10)', type: 'number' },
      { key: 'infrastructure_score', label: 'Infrastructure (0-10)', type: 'number' },
      { key: 'proximity_to_market', label: 'Market Proximity (0-10)', type: 'number' },
      { key: 'tax_incentives', label: 'Tax Incentives', type: 'textarea' },
      { key: 'utilities_cost', label: 'Utilities Cost', type: 'number' },
      { key: 'overall_score', label: 'Overall Score (0-10)', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['evaluating', 'shortlisted', 'selected', 'rejected'], default: 'evaluating' },
    ]
  },
  inventory: {
    titleField: 'item_name',
    tableFields: [
      { key: 'item_name', label: 'Item' },
      { key: 'sku', label: 'SKU' },
      { key: 'category', label: 'Category' },
      { key: 'current_stock', label: 'Stock' },
      { key: 'reorder_point', label: 'Reorder' },
      { key: 'unit_cost', label: 'Unit Cost', type: 'currency' },
      { key: 'stockout_risk', label: 'Risk', type: 'status' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'item_name', label: 'Item Name', required: true },
      { key: 'sku', label: 'SKU' },
      { key: 'category', label: 'Category', type: 'select', options: ['Raw Materials', 'Components', 'Tooling', 'Packaging'] },
      { key: 'current_stock', label: 'Current Stock', type: 'number' },
      { key: 'reorder_point', label: 'Reorder Point', type: 'number' },
      { key: 'optimal_stock', label: 'Optimal Stock', type: 'number' },
      { key: 'lead_time_days', label: 'Lead Time (days)', type: 'number' },
      { key: 'unit_cost', label: 'Unit Cost', type: 'number' },
      { key: 'holding_cost_pct', label: 'Holding Cost %', type: 'number' },
      { key: 'stockout_risk', label: 'Stockout Risk', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] },
      { key: 'supplier_name', label: 'Supplier' },
      { key: 'warehouse_location', label: 'Warehouse Location' },
      { key: 'status', label: 'Status', type: 'select', options: ['in_stock', 'low_stock', 'critical', 'out_of_stock'], default: 'in_stock' },
    ]
  },
  'demand-forecasts': {
    titleField: 'product_name',
    tableFields: [
      { key: 'product_name', label: 'Product' },
      { key: 'category', label: 'Category' },
      { key: 'region', label: 'Region' },
      { key: 'current_demand', label: 'Current' },
      { key: 'forecasted_demand', label: 'Forecast' },
      { key: 'growth_rate', label: 'Growth', type: 'percentage' },
      { key: 'market_trend', label: 'Trend', type: 'status' },
    ],
    formFields: [
      { key: 'product_name', label: 'Product Name', required: true },
      { key: 'category', label: 'Category' },
      { key: 'region', label: 'Region' },
      { key: 'forecast_period', label: 'Forecast Period' },
      { key: 'current_demand', label: 'Current Demand', type: 'number' },
      { key: 'forecasted_demand', label: 'Forecasted Demand', type: 'number' },
      { key: 'growth_rate', label: 'Growth Rate %', type: 'number' },
      { key: 'confidence_level', label: 'Confidence %', type: 'number' },
      { key: 'seasonal_factor', label: 'Seasonal Factor', type: 'number' },
      { key: 'market_trend', label: 'Market Trend', type: 'select', options: ['Explosive Growth', 'Rapid Growth', 'Strong Growth', 'Moderate Growth', 'Steady Growth', 'Recovery Growth', 'Recovery', 'Stable Growth', 'Stable', 'Flat', 'Decline'] },
      { key: 'external_factors', label: 'External Factors', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'archived'], default: 'active' },
    ]
  },
  'quality-assessments': {
    titleField: 'product_name',
    tableFields: [
      { key: 'product_name', label: 'Product' },
      { key: 'supplier_name', label: 'Supplier' },
      { key: 'assessment_type', label: 'Type' },
      { key: 'quality_score', label: 'Score', type: 'score' },
      { key: 'defect_rate', label: 'Defect %', type: 'percentage' },
      { key: 'inspection_date', label: 'Date' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'product_name', label: 'Product Name', required: true },
      { key: 'supplier_name', label: 'Supplier Name' },
      { key: 'assessment_type', label: 'Assessment Type', type: 'select', options: ['Incoming Inspection', 'Process Audit', 'First Article', 'Material Testing', 'Dimensional Audit', 'Stability Testing', 'Certificate of Analysis', 'Assay Report', 'Visual/Physical', 'NDT Inspection', 'Functional Test', 'Compression Test', 'Hardness/Wear Test', 'EL Imaging Test', 'Biocompatibility', 'Food Safety Audit'] },
      { key: 'quality_score', label: 'Quality Score (0-10)', type: 'number' },
      { key: 'defect_rate', label: 'Defect Rate %', type: 'number' },
      { key: 'inspection_date', label: 'Inspection Date', type: 'date' },
      { key: 'standards_met', label: 'Standards Met', type: 'textarea' },
      { key: 'issues_found', label: 'Issues Found', type: 'textarea' },
      { key: 'corrective_actions', label: 'Corrective Actions', type: 'textarea' },
      { key: 'auditor', label: 'Auditor' },
      { key: 'next_review_date', label: 'Next Review Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['passed', 'conditional', 'failed'], default: 'passed' },
    ]
  },
  'environmental-impacts': {
    titleField: 'title',
    tableFields: [
      { key: 'title', label: 'Assessment' },
      { key: 'category', label: 'Category' },
      { key: 'scope', label: 'Scope' },
      { key: 'current_emissions', label: 'Emissions (tons)' },
      { key: 'reduction_target', label: 'Target', type: 'percentage' },
      { key: 'sustainability_score', label: 'Score', type: 'score' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Carbon Emissions', 'Water', 'Waste', 'Land/Ecosystem', 'Multiple'] },
      { key: 'scope', label: 'Scope', type: 'select', options: ['Scope 1', 'Scope 1+2', 'Scope 3', 'Scope 1+2+3', 'Scope 1+3', 'Operations'] },
      { key: 'current_emissions', label: 'Current Emissions (tons)', type: 'number' },
      { key: 'projected_emissions', label: 'Projected Emissions (tons)', type: 'number' },
      { key: 'reduction_target', label: 'Reduction Target %', type: 'number' },
      { key: 'carbon_offset_cost', label: 'Carbon Offset Cost', type: 'number' },
      { key: 'water_usage', label: 'Water Usage (gallons)', type: 'number' },
      { key: 'waste_generated', label: 'Waste Generated (tons)', type: 'number' },
      { key: 'sustainability_score', label: 'Sustainability Score (0-10)', type: 'number' },
      { key: 'initiatives', label: 'Initiatives', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['assessed', 'in_progress', 'completed'], default: 'assessed' },
    ]
  },
  'trade-agreements': {
    titleField: 'agreement_name',
    tableFields: [
      { key: 'agreement_name', label: 'Agreement' },
      { key: 'countries', label: 'Countries' },
      { key: 'agreement_type', label: 'Type' },
      { key: 'tariff_reduction', label: 'Tariff Cut', type: 'percentage' },
      { key: 'effective_date', label: 'Effective' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'agreement_name', label: 'Agreement Name', required: true },
      { key: 'countries', label: 'Countries', type: 'textarea' },
      { key: 'agreement_type', label: 'Type', type: 'select', options: ['Free Trade Agreement', 'Limited Trade Agreement', 'Industrial Policy', 'National Security Tariff', 'Trade Remedies', 'Preferential Trade', 'Economic Framework', 'Procurement Policy', 'Negotiations'] },
      { key: 'effective_date', label: 'Effective Date', type: 'date' },
      { key: 'expiry_date', label: 'Expiry Date', type: 'date' },
      { key: 'tariff_reduction', label: 'Tariff Reduction %', type: 'number' },
      { key: 'key_provisions', label: 'Key Provisions', type: 'textarea' },
      { key: 'affected_industries', label: 'Affected Industries', type: 'textarea' },
      { key: 'rules_of_origin', label: 'Rules of Origin', type: 'textarea' },
      { key: 'benefits', label: 'Benefits', type: 'textarea' },
      { key: 'limitations', label: 'Limitations', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'negotiating'], default: 'active' },
    ]
  },
  'budget-plans': {
    titleField: 'title',
    tableFields: [
      { key: 'title', label: 'Budget Plan' },
      { key: 'category', label: 'Category' },
      { key: 'allocated_budget', label: 'Allocated', type: 'currency' },
      { key: 'spent_to_date', label: 'Spent', type: 'currency' },
      { key: 'variance', label: 'Variance', type: 'currency' },
      { key: 'priority', label: 'Priority', type: 'status' },
      { key: 'roi_expected', label: 'ROI', type: 'percentage' },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    formFields: [
      { key: 'title', label: 'Title', required: true },
      { key: 'category', label: 'Category', type: 'select', options: ['Capital Investment', 'Strategic Investment', 'Operating', 'Technology', 'Contingency'] },
      { key: 'fiscal_year', label: 'Fiscal Year' },
      { key: 'allocated_budget', label: 'Allocated Budget', type: 'number' },
      { key: 'spent_to_date', label: 'Spent to Date', type: 'number' },
      { key: 'projected_total', label: 'Projected Total', type: 'number' },
      { key: 'variance', label: 'Variance', type: 'number' },
      { key: 'priority', label: 'Priority', type: 'select', options: ['Critical', 'High', 'Medium', 'Low'] },
      { key: 'department', label: 'Department' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'milestones', label: 'Milestones', type: 'textarea' },
      { key: 'roi_expected', label: 'Expected ROI %', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'on_hold', 'completed'], default: 'active' },
    ]
  },
};

export function getFieldConfig(featureKey) {
  return configs[featureKey] || {
    titleField: 'name',
    tableFields: [{ key: 'id', label: 'ID' }],
    formFields: []
  };
}
